FROM jupyterhub/k8s-hub:3.0.0

# RUN pip3 install --no-cache-dir jupyterhub-jwtauthenticator-v2
RUN pip3 install --no-cache-dir git+https://github.com/chiayi/ai-on-gke/@refactor-kuberay#subdirectory=ray-on-gke/user/jupyterhub/auth/