# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
hub:
  image: 
    name: gcr.io/aaronliang-agones-gke-dev/k8s-hub
    tag: latest
  # config:
    # JupyterHub:
    #   authenticator_class: 'gcpiapjwtauthenticator.gcpiapjwtauthenticator.GCPIAPAuthenticator'
    # JSONWebTokenAuthenticator:
    #   header_name: X-Goog-Iap-Jwt-Assertion
    #   expected_audience: '/projects/1085966111635/global/backendServices/2826858781982675734'
    #   template_to_render: 'welcome.html'
    #   # Retrieved from https://www.gstatic.com/iap/verify/public_key
    #   secret: |
    #     {
    #       "0oeLcQ" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEMdhRXGEoGJLtBjQEIjnYLPkeci9r\nXnca2TffkI0Kac30GhEQd9fuDk4rwQukD/hFw6cUIZKN9HhIZmkGjuO4Rg==\n-----END PUBLIC KEY-----\n",
    #       "LYyP2g" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESlXFFkJ3JxMsXyXNrqzE3ozl/091\n3PmNbccLLWfeQFUYtJqGtl8ESuYxRwc/QwZp5Wcl0HCq6GuFDx4/Tk18Ig==\n-----END PUBLIC KEY-----\n",
    #       "b9vTLA" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEqCByTAvci+jRAD7uQSEhTdOs8iA7\n14IbcY2L++YzynJZBjS4KhDI9KjNYoZDRqeYV44fkk1eJlr2LpI2o5ybvA==\n-----END PUBLIC KEY-----\n",
    #       "g5X6ig" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE115LSuaFVzVROJiGfdPN1kT14Hv3\nP4RIjthfslZ010v4UBpG07jK+s3i4nz3HAZY4QlxLCkuYU61vRIMnEQC5w==\n-----END PUBLIC KEY-----\n",
    #       "mpf0DA" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfHEdeT3a6KaC1kbwov73ZwB/SiUH\nEyKQwUUtMCEn0aJBY6PA+Eic24+WqPEtDKG95elao4VxA+Fne36Sgw1tkg==\n-----END PUBLIC KEY-----\n"
    #     }
  extraConfig: 
    auth: |
      from urllib import request
      c.JupyterHub.authenticator_class = 'gcpiapjwtauthenticator.GCPIAPAuthenticator'
      c.GCPIAPAuthenticator.header_name = 'X-Goog-IAP-JWT-Assertion'
      c.GCPIAPAuthenticator.expected_audience = '/projects/1085966111635/global/backendServices/3398454410081248856'
      c.GCPIAPAuthenticator.template_to_render = 'welcome.html'
      c.GCPIAPAuthenticator.secret = request.urlopen('https://www.gstatic.com/iap/verify/public_key').read()
    # c.GCPIAPAuthenticator.secret = """
    # {
    #   "0oeLcQ" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEMdhRXGEoGJLtBjQEIjnYLPkeci9r\nXnca2TffkI0Kac30GhEQd9fuDk4rwQukD/hFw6cUIZKN9HhIZmkGjuO4Rg==\n-----END PUBLIC KEY-----\n",
    #   "LYyP2g" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESlXFFkJ3JxMsXyXNrqzE3ozl/091\n3PmNbccLLWfeQFUYtJqGtl8ESuYxRwc/QwZp5Wcl0HCq6GuFDx4/Tk18Ig==\n-----END PUBLIC KEY-----\n",
    #   "b9vTLA" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEqCByTAvci+jRAD7uQSEhTdOs8iA7\n14IbcY2L++YzynJZBjS4KhDI9KjNYoZDRqeYV44fkk1eJlr2LpI2o5ybvA==\n-----END PUBLIC KEY-----\n",
    #   "g5X6ig" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE115LSuaFVzVROJiGfdPN1kT14Hv3\nP4RIjthfslZ010v4UBpG07jK+s3i4nz3HAZY4QlxLCkuYU61vRIMnEQC5w==\n-----END PUBLIC KEY-----\n",
    #   "mpf0DA" : "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfHEdeT3a6KaC1kbwov73ZwB/SiUH\nEyKQwUUtMCEn0aJBY6PA+Eic24+WqPEtDKG95elao4VxA+Fne36Sgw1tkg==\n-----END PUBLIC KEY-----\n"
    # }
    # """
  networkPolicy:
    enabled: false

prePuller:
  hook:
    enabled: false

proxy:
  chp:
    networkPolicy:
      enabled: false
  service:
    type: NodePort
    annotations: 
      beta.cloud.google.com/backend-config: '{"default": "config-default"}'
  traefik:
    networkPolicy:
      enabled: false

scheduling:
  userScheduler:
    enabled: false

singleuser:
  memory:
    limit: 1G
    guarantee: 1G
  cpu:
    limit: .6
    guarantee: .5
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  image:
    name: jupyter/tensorflow-notebook
    tag: python-3.10
  startTimeout: 1000
# More info on kubespawner overrides: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner
#   profile example:
#   - display_name: "Learning Data Science"
#      description: "Datascience Environment with Sample Notebooks"
#      kubespawner_override:
#           cpu_limit: .5
#           cpu_guarantee: .5
#           mem_limit: 1G
#           mem_guarantee: 1G
#        image: jupyter/datascience-notebook:2343e33dec46
#        lifecycle_hooks:
#          postStart:
#            exec:
#              command:
#                - "sh"
#                - "-c"
#                - >
#                  gitpuller https://github.com/data-8/materials-fa17 master materials-fa;
  profileList:
    - display_name: "Profile1 name"
      description: "description here"
      default: true
    # - display_name: "Profile2 name"
    #   description: "description here"
    #   kubespawner_override:
    #     image: <image-name>:<tag>
    #     extra_resource_limits:
    #       # number of gpus needed on the node
    #       nvidia.com/gpu: "2"
    #   #  possible values: nvidia-tesla-k80, nvidia-tesla-p100, nvidia-tesla-p4, nvidia-tesla-v100, nvidia-tesla-t4, nvidia-tesla-a100, nvidia-a100-80gb, nvidia-l4
    #     node_selector:
    #       cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    # - display_name: "Profile3 name"
    #   description: "description"
    #   kubespawner_override:
    #     image: <image-name>:<tag>
    #     extra_resource_limits:
    #       nvidia.com/gpu: "2"
    #     # GPU requests 
    #     extra_resource_guarantees:
    #       nvidia.com/gpu: "2"
    #     node_selector:
    #       cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
  cmd: null
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
